"use client"

import { useEffect, useRef } from "react"
import { usePathname, useRouter } from "next/navigation"
import { ArchitectJobStore, type ArchitectJob } from "@/lib/architect/job-store"
import { createBrowserSupabaseClient } from "@/lib/supabase/client"

/**
 * Mounts once in the root layout (inside AuthenticatedShell or equivalent).
 * Watches the ArchitectJobStore and:
 *  1. Shows a browser toast when generation completes, regardless of current page.
 *  2. Inserts a Supabase notification row so the notification bell also lights up.
 *  3. Shows a persistent "Architect is running…" banner when on a different page.
 */
export function ArchitectJobProvider({ userId }: { userId: string | null }) {
  const pathname = usePathname()
  const router = useRouter()
  const prevStatus = useRef<string>("idle")
  const supabase = createBrowserSupabaseClient()

  useEffect(() => {
    const unsub = ArchitectJobStore.subscribe(async (job: ArchitectJob) => {
      const onArchitectPage = pathname?.startsWith("/architect")

      // Transition to done
      if (job.status === "done" && prevStatus.current === "running") {
        prevStatus.current = "done"
        const fileCount = Object.keys(job.completedFiles).length

        // Insert Supabase notification (realtime will pop the toast via NotificationProvider)
        if (userId) {
          await supabase.from("notifications").insert({
            user_id: userId,
            type: "architect_complete",
            title: "Project files ready",
            message: `${job.projectName} — ${fileCount} file${fileCount !== 1 ? "s" : ""} generated successfully.`,
            priority: "HIGH",
            action_url: "/architect",
            action_label: "View files",
            icon_name: "Sparkles",
            read: false,
          }).then(({ error }) => {
            if (error) console.error("[ArchitectJobProvider] notification insert:", error)
          })
        }

        // If NOT on architect page, also show a native browser notification (if permitted)
        if (!onArchitectPage && typeof window !== "undefined") {
          if (Notification.permission === "granted") {
            new Notification(`${job.projectName} is ready`, {
              body: `${fileCount} project files generated by Midas Architect.`,
              icon: "/favicon.ico",
            })
          } else if (Notification.permission === "default") {
            Notification.requestPermission().then(perm => {
              if (perm === "granted") {
                new Notification(`${job.projectName} is ready`, {
                  body: `${fileCount} project files generated by Midas Architect.`,
                  icon: "/favicon.ico",
                })
              }
            })
          }
        }
      }

      // Transition to error
      if (job.status === "error" && prevStatus.current === "running") {
        prevStatus.current = "error"
        if (userId) {
          await supabase.from("notifications").insert({
            user_id: userId,
            type: "architect_error",
            title: "Architect generation failed",
            message: job.error ?? "An unknown error occurred during file generation.",
            priority: "HIGH",
            action_url: "/architect",
            action_label: "Try again",
            icon_name: "AlertTriangle",
            read: false,
          })
        }
      }

      if (job.status === "running") prevStatus.current = "running"
      if (job.status === "idle") prevStatus.current = "idle"
    })

    return unsub
  }, [pathname, userId, supabase])

  // Render the floating background-run banner when on a different page
  return <ArchitectRunningBanner />
}

function ArchitectRunningBanner() {
  const pathname = usePathname()
  const router = useRouter()
  const jobRef = useRef<ArchitectJob | null>(null)
  const forceUpdate = useRef<(() => void) | null>(null)

  // Simple subscription to force re-render
  useEffect(() => {
    let mounted = true
    const unsub = ArchitectJobStore.subscribe(job => {
      jobRef.current = job
      if (mounted && forceUpdate.current) forceUpdate.current()
    })
    return () => { mounted = false; unsub() }
  }, [])

  // Force re-render trick using a counter stored in ref
  const counterRef = useRef(0)
  forceUpdate.current = () => { counterRef.current++ }

  const job = jobRef.current
  const onArchitectPage = pathname?.startsWith("/architect")

  if (!job || job.status !== "running" || onArchitectPage) return null

  const done = Object.keys(job.completedFiles).length
  const pct = job.totalFiles > 0 ? Math.round((done / job.totalFiles) * 100) : 0

  return (
    <div className="fixed bottom-4 right-4 z-[9999] flex flex-col gap-2 pointer-events-none">
      <div
        className="pointer-events-auto flex items-center gap-3 bg-zinc-900 border border-amber-500/40 rounded-2xl px-4 py-3 shadow-2xl shadow-black/50 cursor-pointer hover:border-amber-400/60 transition-all"
        onClick={() => router.push("/architect")}
      >
        <div className="w-8 h-8 rounded-lg bg-amber-500/20 border border-amber-500/30 flex items-center justify-center flex-shrink-0">
          <span className="text-amber-400 text-xs font-bold animate-pulse">AI</span>
        </div>
        <div className="min-w-0">
          <div className="text-xs font-semibold text-white truncate">
            {job.projectName || "Architect"}
          </div>
          <div className="text-[10px] text-amber-400/80 mt-0.5 font-medium">
            {job.currentFile ? `Coding ${job.currentFile}…` : `Coding — ${done}/${job.totalFiles} files`}
          </div>
        </div>
        <div className="flex-shrink-0 ml-2">
          <div className="w-8 h-8 relative">
            <svg viewBox="0 0 32 32" className="-rotate-90 w-8 h-8">
              <circle cx="16" cy="16" r="13" fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="2.5" />
              <circle
                cx="16" cy="16" r="13" fill="none"
                stroke="#f59e0b" strokeWidth="2.5"
                strokeDasharray={`${(pct / 100) * 81.7} 81.7`}
                strokeLinecap="round"
                style={{ transition: "stroke-dasharray 0.5s ease" }}
              />
            </svg>
            <span className="absolute inset-0 flex items-center justify-center text-[9px] font-bold text-amber-400">{pct}%</span>
          </div>
        </div>
      </div>
    </div>
  )
}
