export interface CategoryDefinition {
  name: string
  slug: string
  description: string
  keywords: string[]
  aliases: string[]
  displayGroup: string
}

export const OFFICIAL_CATEGORIES: CategoryDefinition[] = [
  // AI Assistants
  {
    name: "Claude Code Skills",
    slug: "claude-code-skills",
    description: "Skills, prompts, and instructions designed specifically for Claude Code.",
    keywords: ["claude", "claude code", "claude skills", "anthropic", "claude-md", "claude-instructions"],
    aliases: ["claude", "claude-code", "claude-skills"],
    displayGroup: "AI Assistant",
  },
  {
    name: "Cursor Rules",
    slug: "cursor-rules",
    description: "Rules, context, and conventions for Cursor editor and AI coding.",
    keywords: ["cursor", "cursor rules", "cursorrules", ".cursorrules", "cursor-ai", "cursor editor"],
    aliases: ["cursor", "cursorrules"],
    displayGroup: "AI Assistant",
  },
  {
    name: "Codex Agents",
    slug: "codex-agents",
    description: "Agents and prompts for OpenAI Codex CLI.",
    keywords: ["codex", "openai codex", "codex cli", "codex agent"],
    aliases: ["codex", "openai-codex"],
    displayGroup: "AI Assistant",
  },
  {
    name: "Windsurf Workflows",
    slug: "windsurf-workflows",
    description: "Workflows and rules for Windsurf IDE.",
    keywords: ["windsurf", "windsurf ide", "codeium", "windsurf workflow"],
    aliases: ["windsurf", "windsurf-ide"],
    displayGroup: "AI Assistant",
  },
  {
    name: "ChatGPT Prompts",
    slug: "chatgpt-prompts",
    description: "Prompts, custom instructions, and GPTs for ChatGPT.",
    keywords: ["chatgpt", "gpt", "openai", "custom instructions", "gpt prompts"],
    aliases: ["chatgpt", "gpt"],
    displayGroup: "AI Assistant",
  },
  {
    name: "Gemini Gems",
    slug: "gemini-gems",
    description: "Gems, memory, and instructions for Google Gemini.",
    keywords: ["gemini", "google gemini", "gemini gem", "gemini instructions"],
    aliases: ["gemini", "google-gemini"],
    displayGroup: "AI Assistant",
  },
  // Types
  {
    name: "AI Agents",
    slug: "ai-agents",
    description: "Autonomous agents that perform tasks with tools and reasoning.",
    keywords: ["agent", "agents", "autonomous", "reAct", "tool use", "agentic"],
    aliases: ["agent", "agents", "autonomous-agent"],
    displayGroup: "Type",
  },
  {
    name: "Workflow Templates",
    slug: "workflow-templates",
    description: "Reusable multi-step AI workflows and pipelines.",
    keywords: ["workflow", "pipeline", "automation", "sequence", "steps", "n8n", "zapier"],
    aliases: ["workflow", "workflows", "pipeline"],
    displayGroup: "Type",
  },
  {
    name: "Architect Blueprints",
    slug: "architect-blueprints",
    description: "Complete project architecture, file structure, and scaffolding blueprints.",
    keywords: ["blueprint", "architecture", "scaffold", "project structure", "boilerplate"],
    aliases: ["blueprint", "architecture", "scaffold"],
    displayGroup: "Type",
  },
  {
    name: "Prompt Packs",
    slug: "prompt-packs",
    description: "Curated libraries of prompts for specific tasks and roles.",
    keywords: ["prompt", "prompts", "prompt library", "prompt pack", "prompt engineering"],
    aliases: ["prompt", "prompts", "prompt-library"],
    displayGroup: "Type",
  },
  {
    name: "Automation",
    slug: "automation",
    description: "Automations, scripts, and bots that remove manual work.",
    keywords: ["automation", "automate", "bot", "script", "cron", "scheduler"],
    aliases: ["automation", "automate"],
    displayGroup: "Type",
  },
  {
    name: "Memory Systems",
    slug: "memory-systems",
    description: "Long-term context, memory, and knowledge management for AI assistants.",
    keywords: ["memory", "context", "knowledge base", "remember", "long-term memory", "RAG"],
    aliases: ["memory", "context", "knowledge-base"],
    displayGroup: "Type",
  },
  {
    name: "Documentation",
    slug: "documentation",
    description: "README, specs, runbooks, and technical documentation templates.",
    keywords: ["documentation", "readme", "docs", "runbook", "spec", "wiki"],
    aliases: ["docs", "readme", "documentation"],
    displayGroup: "Type",
  },
  {
    name: "Development Tools",
    slug: "development-tools",
    description: "IDE plugins, CLI tools, dev utilities, and DX improvements.",
    keywords: ["developer tools", "cli", "plugin", "extension", "dx", "devtool"],
    aliases: ["devtools", "developer-tools", "cli-tool"],
    displayGroup: "Type",
  },
  {
    name: "Utilities",
    slug: "utilities",
    description: "General-purpose utility skills and helper tools.",
    keywords: ["utility", "utilities", "helper", "tool", "snippet"],
    aliases: ["utility", "utilities", "helper"],
    displayGroup: "Type",
  },
  {
    name: "Open Source",
    slug: "open-source",
    description: "Open source projects, contributions, and community tools.",
    keywords: ["open source", "oss", "github", "contribution", "community"],
    aliases: ["oss", "open-source", "github"],
    displayGroup: "Type",
  },
  // Domains
  {
    name: "Frontend",
    slug: "frontend",
    description: "UI, design, styling, and client-side development.",
    keywords: ["frontend", "ui", "ux", "client-side", "browser", "html", "css"],
    aliases: ["frontend", "ui", "client-side"],
    displayGroup: "Domain",
  },
  {
    name: "Backend",
    slug: "backend",
    description: "Server-side logic, APIs, databases, and infrastructure code.",
    keywords: ["backend", "server", "server-side", "api", "microservice"],
    aliases: ["backend", "server-side"],
    displayGroup: "Domain",
  },
  {
    name: "Full Stack",
    slug: "full-stack",
    description: "End-to-end projects spanning frontend and backend.",
    keywords: ["full stack", "fullstack", "end-to-end", "e2e"],
    aliases: ["fullstack", "full-stack", "end-to-end"],
    displayGroup: "Domain",
  },
  {
    name: "API Development",
    slug: "api-development",
    description: "REST, GraphQL, RPC, and API design tooling.",
    keywords: ["api", "rest", "graphql", "rpc", "endpoint", "swagger", "openapi"],
    aliases: ["api", "rest-api", "graphql"],
    displayGroup: "Domain",
  },
  {
    name: "Database",
    slug: "database",
    description: "Database schemas, queries, migrations, and ORM tooling.",
    keywords: ["database", "db", "sql", "schema", "migration", "orm"],
    aliases: ["database", "db", "sql"],
    displayGroup: "Domain",
  },
  {
    name: "Authentication",
    slug: "authentication",
    description: "Auth, identity, SSO, OAuth, and access control.",
    keywords: ["authentication", "auth", "oauth", "sso", "login", "identity", "jwt"],
    aliases: ["auth", "authentication", "oauth"],
    displayGroup: "Domain",
  },
  {
    name: "Security",
    slug: "security",
    description: "Security audits, hardening, secrets, and best practices.",
    keywords: ["security", "secure", "hardening", "vulnerability", "secrets", "penetration"],
    aliases: ["security", "secure", "hardening"],
    displayGroup: "Domain",
  },
  {
    name: "DevOps",
    slug: "devops",
    description: "CI/CD, infrastructure as code, and platform engineering.",
    keywords: ["devops", "infrastructure", "iac", "platform", "deployment", "release"],
    aliases: ["devops", "infrastructure", "platform"],
    displayGroup: "Domain",
  },
  {
    name: "Mobile",
    slug: "mobile",
    description: "Mobile development and cross-platform apps.",
    keywords: ["mobile", "ios", "android", "app", "cross-platform"],
    aliases: ["mobile", "ios", "android"],
    displayGroup: "Domain",
  },
  {
    name: "Machine Learning",
    slug: "machine-learning",
    description: "ML models, training, inference, and AI pipelines.",
    keywords: ["machine learning", "ml", "model", "training", "inference", "ai"],
    aliases: ["machine-learning", "ml", "ai-model"],
    displayGroup: "Domain",
  },
  {
    name: "AI Productivity",
    slug: "ai-productivity",
    description: "Productivity and personal assistant workflows.",
    keywords: ["productivity", "assistant", "personal assistant", "efficiency"],
    aliases: ["productivity", "ai-productivity", "assistant"],
    displayGroup: "Domain",
  },
  {
    name: "Business Automation",
    slug: "business-automation",
    description: "Business process automation and enterprise workflows.",
    keywords: ["business", "enterprise", "bpa", "workflow automation", "operations"],
    aliases: ["business-automation", "enterprise", "bpa"],
    displayGroup: "Domain",
  },
  {
    name: "Content Creation",
    slug: "content-creation",
    description: "AI content generation, editing, and creative tools.",
    keywords: ["content", "creative", "writing", "blog", "copywriting", "generation"],
    aliases: ["content-creation", "creative", "writing"],
    displayGroup: "Domain",
  },
  {
    name: "Marketing",
    slug: "marketing",
    description: "Marketing automation, campaigns, and growth tools.",
    keywords: ["marketing", "growth", "campaign", "ads", "email marketing"],
    aliases: ["marketing", "growth", "campaign"],
    displayGroup: "Domain",
  },
  {
    name: "Sales",
    slug: "sales",
    description: "Sales automation, CRM, and outreach tools.",
    keywords: ["sales", "crm", "outreach", "lead", "prospecting"],
    aliases: ["sales", "crm", "outreach"],
    displayGroup: "Domain",
  },
  {
    name: "SEO",
    slug: "seo",
    description: "Search engine optimization and keyword tools.",
    keywords: ["seo", "search", "keywords", "ranking", "optimization"],
    aliases: ["seo", "search-engine"],
    displayGroup: "Domain",
  },
  {
    name: "Data Analysis",
    slug: "data-analysis",
    description: "Data analysis, visualization, and BI tools.",
    keywords: ["data", "analytics", "visualization", "bi", "pandas", "dataframe"],
    aliases: ["data-analysis", "analytics", "bi"],
    displayGroup: "Domain",
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Finance, accounting, and trading automation.",
    keywords: ["finance", "accounting", "trading", "crypto", "fintech"],
    aliases: ["finance", "fintech", "accounting"],
    displayGroup: "Domain",
  },
  {
    name: "Education",
    slug: "education",
    description: "Education, tutoring, and learning tools.",
    keywords: ["education", "learning", "tutor", "course", "teaching"],
    aliases: ["education", "learning", "teaching"],
    displayGroup: "Domain",
  },
  // DevOps
  {
    name: "Docker",
    slug: "docker",
    description: "Containerization with Docker and Docker Compose.",
    keywords: ["docker", "container", "dockerfile", "docker compose", "containerization"],
    aliases: ["docker", "container", "dockerfile"],
    displayGroup: "DevOps",
  },
  {
    name: "Kubernetes",
    slug: "kubernetes",
    description: "Container orchestration with Kubernetes.",
    keywords: ["kubernetes", "k8s", "helm", "pod", "deployment"],
    aliases: ["kubernetes", "k8s", "helm"],
    displayGroup: "DevOps",
  },
  {
    name: "Cloud",
    slug: "cloud",
    description: "Multi-cloud and cloud-native skills.",
    keywords: ["cloud", "cloud-native", "serverless", "paas", "iaas"],
    aliases: ["cloud", "cloud-native", "serverless"],
    displayGroup: "DevOps",
  },
  {
    name: "AWS",
    slug: "aws",
    description: "Amazon Web Services skills and patterns.",
    keywords: ["aws", "amazon web services", "lambda", "s3", "ec2", "cloudformation"],
    aliases: ["aws", "amazon-web-services"],
    displayGroup: "Cloud",
  },
  {
    name: "Azure",
    slug: "azure",
    description: "Microsoft Azure skills and patterns.",
    keywords: ["azure", "microsoft azure", "azure functions", "az"],
    aliases: ["azure", "microsoft-azure"],
    displayGroup: "Cloud",
  },
  {
    name: "Google Cloud",
    slug: "google-cloud",
    description: "Google Cloud Platform skills and patterns.",
    keywords: ["gcp", "google cloud", "google cloud platform", "gcloud"],
    aliases: ["gcp", "google-cloud", "google-cloud-platform"],
    displayGroup: "Cloud",
  },
  {
    name: "CI/CD",
    slug: "ci-cd",
    description: "Continuous integration and delivery pipelines.",
    keywords: ["ci/cd", "cicd", "continuous integration", "github actions", "gitlab ci"],
    aliases: ["cicd", "ci-cd", "continuous-integration"],
    displayGroup: "DevOps",
  },
  {
    name: "Testing",
    slug: "testing",
    description: "Unit, integration, E2E, and load testing.",
    keywords: ["testing", "test", "jest", "pytest", "cypress", "playwright", "unit test"],
    aliases: ["testing", "tests", "unit-test"],
    displayGroup: "DevOps",
  },
  {
    name: "Debugging",
    slug: "debugging",
    description: "Debugging tools and techniques.",
    keywords: ["debug", "debugging", "trace", "profiler", "logging"],
    aliases: ["debugging", "debug", "trace"],
    displayGroup: "DevOps",
  },
  {
    name: "Performance",
    slug: "performance",
    description: "Performance optimization and profiling.",
    keywords: ["performance", "optimize", "speed", "latency", "profiler"],
    aliases: ["performance", "optimization", "profiling"],
    displayGroup: "DevOps",
  },
  {
    name: "Monitoring",
    slug: "monitoring",
    description: "Observability, monitoring, and alerting.",
    keywords: ["monitoring", "observability", "alerting", "metrics", "dashboard"],
    aliases: ["monitoring", "observability", "alerting"],
    displayGroup: "DevOps",
  },
  {
    name: "Logging",
    slug: "logging",
    description: "Logging, log aggregation, and tracing.",
    keywords: ["logging", "logs", "log aggregation", "tracing", "syslog"],
    aliases: ["logging", "logs", "log-aggregation"],
    displayGroup: "DevOps",
  },
  // Frameworks
  {
    name: "React",
    slug: "react",
    description: "React skills, components, hooks, and patterns.",
    keywords: ["react", "reactjs", "jsx", "hooks", "component"],
    aliases: ["react", "reactjs", "react-js"],
    displayGroup: "Framework",
  },
  {
    name: "Next.js",
    slug: "next-js",
    description: "Next.js skills, App Router, API routes, and deployment.",
    keywords: ["nextjs", "next.js", "next", "app router", "api routes"],
    aliases: ["nextjs", "next-js", "next"],
    displayGroup: "Framework",
  },
  {
    name: "Vue",
    slug: "vue",
    description: "Vue.js skills, composition API, and patterns.",
    keywords: ["vue", "vuejs", "vue.js", "composition api", "vuex"],
    aliases: ["vue", "vuejs", "vue-js"],
    displayGroup: "Framework",
  },
  {
    name: "Angular",
    slug: "angular",
    description: "Angular skills, components, and patterns.",
    keywords: ["angular", "angularjs", "ng", "typescript"],
    aliases: ["angular", "angular-js", "ng"],
    displayGroup: "Framework",
  },
  {
    name: "Svelte",
    slug: "svelte",
    description: "Svelte and SvelteKit skills.",
    keywords: ["svelte", "sveltekit", "svelte kit", "svelte-js"],
    aliases: ["svelte", "svelte-kit", "sveltekit"],
    displayGroup: "Framework",
  },
  {
    name: "UI Components",
    slug: "ui-components",
    description: "Reusable UI components and component libraries.",
    keywords: ["ui component", "component library", "design system", "ui kit"],
    aliases: ["ui-components", "component-library", "ui-kit"],
    displayGroup: "Frontend",
  },
  {
    name: "TailwindCSS",
    slug: "tailwindcss",
    description: "Tailwind CSS utilities, themes, and patterns.",
    keywords: ["tailwind", "tailwindcss", "tailwind css", "utility-first"],
    aliases: ["tailwind", "tailwindcss", "tailwind-css"],
    displayGroup: "Frontend",
  },
  {
    name: "Design Systems",
    slug: "design-systems",
    description: "Component libraries, design tokens, and design systems.",
    keywords: ["design system", "design tokens", "component library", "storybook"],
    aliases: ["design-system", "design-systems", "design-tokens"],
    displayGroup: "Frontend",
  },
  {
    name: "shadcn/ui",
    slug: "shadcn-ui",
    description: "shadcn/ui components, patterns, and themes.",
    keywords: ["shadcn", "shadcn/ui", "shadcn-ui", "radix", "ui component"],
    aliases: ["shadcn", "shadcn-ui", "shadcnui"],
    displayGroup: "Frontend",
  },
  // Languages
  {
    name: "Node.js",
    slug: "node-js",
    description: "Node.js runtime, packages, and server skills.",
    keywords: ["nodejs", "node.js", "node", "npm", "commonjs", "esm"],
    aliases: ["nodejs", "node-js", "node"],
    displayGroup: "Language",
  },
  {
    name: "Python",
    slug: "python",
    description: "Python skills, libraries, and frameworks.",
    keywords: ["python", "py", "pip", "django", "flask", "fastapi"],
    aliases: ["python", "py", "python3"],
    displayGroup: "Language",
  },
  {
    name: "TypeScript",
    slug: "typescript",
    description: "TypeScript skills, types, and patterns.",
    keywords: ["typescript", "ts", "type", "types", "typed"],
    aliases: ["typescript", "ts", "typed"],
    displayGroup: "Language",
  },
  {
    name: "JavaScript",
    slug: "javascript",
    description: "JavaScript skills, patterns, and runtime.",
    keywords: ["javascript", "js", "es6", "esm", "vanilla js"],
    aliases: ["javascript", "js", "vanilla-js"],
    displayGroup: "Language",
  },
  {
    name: "Go",
    slug: "go",
    description: "Go skills, patterns, and tooling.",
    keywords: ["go", "golang", "go-lang", "goroutines"],
    aliases: ["go", "golang", "go-lang"],
    displayGroup: "Language",
  },
  {
    name: "Rust",
    slug: "rust",
    description: "Rust skills, patterns, and tooling.",
    keywords: ["rust", "rust-lang", "cargo", "tokio"],
    aliases: ["rust", "rust-lang", "rustlang"],
    displayGroup: "Language",
  },
  {
    name: "Java",
    slug: "java",
    description: "Java skills, patterns, and frameworks.",
    keywords: ["java", "spring", "jvm", "maven", "gradle"],
    aliases: ["java", "jvm", "spring-boot"],
    displayGroup: "Language",
  },
  {
    name: "C#",
    slug: "csharp",
    description: "C# skills, .NET, and patterns.",
    keywords: ["c#", "csharp", ".net", "dotnet", "asp.net"],
    aliases: ["csharp", "c-sharp", "dotnet"],
    displayGroup: "Language",
  },
  // Mobile
  {
    name: "React Native",
    slug: "react-native",
    description: "React Native mobile apps and components.",
    keywords: ["react native", "react-native", "expo", "mobile app"],
    aliases: ["react-native", "reactnative", "expo"],
    displayGroup: "Mobile",
  },
  {
    name: "Flutter",
    slug: "flutter",
    description: "Flutter cross-platform apps and widgets.",
    keywords: ["flutter", "dart", "cross-platform", "mobile app"],
    aliases: ["flutter", "dart"],
    displayGroup: "Mobile",
  },
  {
    name: "Swift",
    slug: "swift",
    description: "Swift and iOS development.",
    keywords: ["swift", "ios", "swiftui", "uikit", "apple"],
    aliases: ["swift", "ios", "swiftui"],
    displayGroup: "Mobile",
  },
  {
    name: "Kotlin",
    slug: "kotlin",
    description: "Kotlin and Android development.",
    keywords: ["kotlin", "android", "jetpack compose", "mobile app"],
    aliases: ["kotlin", "android", "jetpack-compose"],
    displayGroup: "Mobile",
  },
  // Backend services
  {
    name: "Supabase",
    slug: "supabase",
    description: "Supabase skills, patterns, and Postgres.",
    keywords: ["supabase", "supabase-js", "postgrest", "realtime", "auth"],
    aliases: ["supabase", "supabase-js"],
    displayGroup: "Backend",
  },
  {
    name: "Firebase",
    slug: "firebase",
    description: "Firebase skills, patterns, and Google backend.",
    keywords: ["firebase", "firestore", "google firebase", "firebase auth"],
    aliases: ["firebase", "firestore"],
    displayGroup: "Backend",
  },
  {
    name: "Postgres",
    slug: "postgres",
    description: "PostgreSQL skills, schemas, queries, and optimization.",
    keywords: ["postgres", "postgresql", "psql", "plpgsql", "sql"],
    aliases: ["postgres", "postgresql", "psql"],
    displayGroup: "Backend",
  },
  {
    name: "MongoDB",
    slug: "mongodb",
    description: "MongoDB skills, schemas, and queries.",
    keywords: ["mongodb", "mongo", "mongoose", "nosql"],
    aliases: ["mongodb", "mongo", "mongoose"],
    displayGroup: "Backend",
  },
  {
    name: "Redis",
    slug: "redis",
    description: "Redis skills, caching, and data structures.",
    keywords: ["redis", "cache", "caching", "key-value", "redis stack"],
    aliases: ["redis", "cache", "caching"],
    displayGroup: "Backend",
  },
  {
    name: "GraphQL",
    slug: "graphql",
    description: "GraphQL APIs, schemas, and clients.",
    keywords: ["graphql", "apollo", "gql", "schema", "resolver"],
    aliases: ["graphql", "gql", "apollo"],
    displayGroup: "API",
  },
  {
    name: "REST APIs",
    slug: "rest-apis",
    description: "REST API design and implementation.",
    keywords: ["rest", "rest api", "restful", "http", "api"],
    aliases: ["rest", "rest-api", "restful"],
    displayGroup: "API",
  },
  // AI
  {
    name: "LLMs",
    slug: "llms",
    description: "Large language model integrations and APIs.",
    keywords: ["llm", "large language model", "openai", "anthropic", "gemini"],
    aliases: ["llm", "llms", "large-language-model"],
    displayGroup: "AI",
  },
  {
    name: "RAG",
    slug: "rag",
    description: "Retrieval-augmented generation and knowledge retrieval.",
    keywords: ["rag", "retrieval augmented generation", "retrieval", "context"],
    aliases: ["rag", "retrieval-augmented-generation"],
    displayGroup: "AI",
  },
  {
    name: "Vector Databases",
    slug: "vector-databases",
    description: "Vector search, embeddings storage, and vector databases.",
    keywords: ["vector database", "vector store", "embedding", "pinecone", "weaviate", "chroma"],
    aliases: ["vector-database", "vector-store", "embeddings"],
    displayGroup: "AI",
  },
  {
    name: "Embeddings",
    slug: "embeddings",
    description: "Embedding models, similarity, and vectorization.",
    keywords: ["embedding", "embeddings", "vector", "similarity", "vectorization"],
    aliases: ["embeddings", "embedding", "vectorization"],
    displayGroup: "AI",
  },
  {
    name: "Prompt Engineering",
    slug: "prompt-engineering",
    description: "Prompt design, optimization, and techniques.",
    keywords: ["prompt engineering", "prompt", "prompting", "prompt design"],
    aliases: ["prompt-engineering", "prompting", "prompt-design"],
    displayGroup: "AI",
  },
  {
    name: "Fine Tuning",
    slug: "fine-tuning",
    description: "Model fine-tuning, adaptation, and training.",
    keywords: ["fine tuning", "fine-tuning", "fine tune", "model training", "lora"],
    aliases: ["fine-tuning", "finetuning", "fine-tune"],
    displayGroup: "AI",
  },
]

export const CATEGORY_SLUGS = OFFICIAL_CATEGORIES.map((c) => c.slug)
export const CATEGORY_NAMES = OFFICIAL_CATEGORIES.map((c) => c.name)

export function getCategoryBySlug(slug: string): CategoryDefinition | undefined {
  return OFFICIAL_CATEGORIES.find((c) => c.slug === slug)
}

export function getCategoryByName(name: string): CategoryDefinition | undefined {
  return OFFICIAL_CATEGORIES.find(
    (c) => c.name.toLowerCase() === name.toLowerCase() || c.slug.toLowerCase() === name.toLowerCase()
  )
}
