"use strict"

/**
 * Project Intelligence Engine
 *
 * Scans every markdown file generated by Architect.
 * Reads every file.
 * Parses every file.
 * Extracts metadata including:
 * - technologies
 * - frameworks
 * - APIs
 * - database
 * - authentication
 * - deployment
 * - testing
 * - security
 * - AI
 * - integrations
 * - dependencies
 * - referenced files
 *
 * Builds an internal representation of the project including:
 * - knowledge graph
 * - relationship mapping
 * - dependency analysis
 * - architectural patterns
 * - technology stack
 */
import { readFileSync, readdirSync } from "fs"
import { join, dirname, basename } from "path"
import { EventEmitter } from "events"
import * as matter from "gray-matter"

type FileMetadata = {
  filePath: string
  category: string
  content: string
  title: string
  description: string
  wordCount: number
  lineCount: number
  sentiment?: string
  technicalLevel?: "beginner" | "intermediate" | "advanced"
  technologies?: Technology[]
  intent?: string
  architecturePattern?: string
  [key: string]: any
}

type Technology = {
  name: string
  type: "language" | "framework" | "library" | "service" | "tool" | "database" | "auth" | "ai" | "testing"
  version?: string
  detectedFrom: string
}

type KnowledgeGraphNode = {
  id: string
  type: "file" | "concept" | "component" | "relationship" | "pattern"
  filePath?: string
  title?: string
  description?: string
  category?: string
  metadata?: Record<string, any>
  confidence: number
  relationships: KnowledgeGraphRelationship[]
}

type KnowledgeGraphRelationship = {
  sourceId: string
  targetId: string
  type: "depends_on" | "references" | "creates" | "uses" | "extends" | "implements"
  confidence: number
  description: string
}

class ProjectIntelligenceEngine extends EventEmitter {
  private findAllMarkdownFiles(root: string): string[] {
    const results: string[] = []

    function walk(dir: string): void {
      try {
        const items = readdirSync(dir, { withFileTypes: true })
        for (const item of items) {
          const fullPath = join(dir, item.name)
          if (item.isDirectory()) {
            walk(fullPath)
          } else if (item.isFile() && item.name.match(/\.(md|markdown)$/i)) {
            results.push(fullPath)
          }
        }
      } catch (error) {
        // Directory might not be readable, skip it
      }
    }

    walk(root)
    return results
  }

  private countWords(content: string): number {
    return content.split(/\s+/).filter(word => word).length
  }

  private countLines(content: string): number {
    return content.split('\n').length
  }

  private extractFrontmatter(content: string): Record<string, any> {
    const { data } = matter(content)
    return data
  }

  private extractMetadata(
    frontmatter: Record<string, any>,
    content: string,
    filePath: string
  ): FileMetadata {
    const contentLower = content.toLowerCase()

    // Categories and related keywords
    const categories: Record<string, string[]> = {
      "language": ["typescript", "javascript", "python", "go", "rust", "java", "c#"],
      "framework": ["next.js", "react", "vue", "angular", "express", "koa", "nest", "fastify"],
      "database": ["postgres", "supabase", "mysql", "sqlite", "mongodb"],
      "auth": ["auth", "session", "token", "jwt", "oauth", "provider"],
      "security": ["security", "rbac", "rls", "policy", "encryption", "ssl", "tls"],
      "deployment": ["deployment", "ci", "cd", "docker", "kubernetes", "aws", "azure", "gcp", "vercel", "netlify"],
      "testing": ["test", "testing", "unit", "integration", "e2e", "playwright", "cypress", "jest", "mocha"],
      "payment": ["stripe", "checkout", "connect"],
      "ai": ["ai", "agent", "workflow", "orchestration", "prompt", "mcp"],
      "architecture": ["architecture", "design", "structure", "pattern", "microservice", "monolith"],
      "documentation": ["readme", "docs", "documentation", "guide", "tutorial"]
    }

    // Detect categories based on content
    const detectedCategories = Object.keys(categories).filter(category =>
      categories[category].some(keyword => contentLower.includes(keyword.toLowerCase()))
    )

    // Choose primary category based on most matches or external hints
    const category = this.getPrimaryCategory(contentLower, detectedCategories, frontmatter, categories)

    // Extract meaningful metadata
    const metadata: FileMetadata = {
      filePath,
      category,
      content,
      title: frontmatter.title || this.extractTitle(content, category),
      description: frontmatter.description || this.extractDescription(content, category),
      wordCount: this.countWords(content),
      lineCount: this.countLines(content),
      shortDescription: frontmatter.description || this.extractShortDescription(content),
      sentiment: frontmatter?.sentiment ? this.analyzeSentiment(frontmatter.sentiment as string) : undefined,
      technicalLevel: frontmatter?.technicalLevel ? this.determineTechnicalLevel(frontmatter.technicalLevel as string) : undefined,
      intent: frontmatter?.intent ? this.inferIntent(frontmatter, content) : undefined,
      architecturePattern: frontmatter?.architecture ? this.detectArchitecturePattern(frontmatter.architecture as string) : undefined,
      technologies: frontmatter?.technologies ? this.extractTechnologies(JSON.stringify(frontmatter.technologies)) : undefined,
    }

    return metadata
  }

  private extractTitle(content: string, defaultCategory: string): string {
    const headingPattern = /^(#{1,6})\s+(.+)$/m
    const match = content.match(headingPattern)
    if (match) {
      // Convert markdown heading to clean title
      let title = match[2].trim()
      title = title.replace(/[^a-zA-Z0-9\s]/g, "")
      title = title.replace(/\s+/g, " ")
      return title.charAt(0).toUpperCase() + title.slice(1)
    }

    // Fallback to filename-based title
    const fileBasename = basename(defaultCategory)
    return fileBasename.replace(/-/g, " ").replace(/\.[^.]+$/, "")
  }

  private extractDescription(content: string, category: string): string {
    // Look for descriptive text after title
    const lines = content.split("\n").filter(line => line.trim())

    // Skip frontmatter if present
    let startIndex = 0
    if (content.startsWith("---")) {
      const endFrontmatter = content.indexOf("\n---\n", 3)
      if (endFrontmatter !== -1) {
        startIndex = endFrontmatter + 4
      }
    }

    const body = content.substring(startIndex)
    const bodyLines = body.split("\n").filter(line => line.trim())

    // Find first substantive line (not empty, not a heading)
    for (const line of bodyLines) {
      const trimmed = line.trim()
      if (trimmed && !trimmed.startsWith("#")) {
        return trimmed.slice(0, 200)
      }
    }

    return bodyLines.find(line => line.trim())?.slice(0, 200) || ""
  }

  private extractShortDescription(content: string): string {
    // Look for first paragraph or description-like text
    const lines = content.split("\n").filter(line => line.trim())

    // Skip frontmatter
    let startIndex = 0
    if (content.startsWith("---")) {
      const endFrontmatter = content.indexOf("\n---\n", 3)
      if (endFrontmatter !== -1) {
        startIndex = endFrontmatter + 4
      }
    }

    const body = content.substring(startIndex)

    // Look for first non-empty line that's not a heading or code fence
    for (const line of body.split("\n")) {
      const trimmed = line.trim()
      if (trimmed &&
          !trimmed.startsWith("#") &&
          !trimmed.startsWith("```") &&
          !trimmed.startsWith(">") &&
          trimmed.length > 10) {
        return trimmed.slice(0, 150)
      }
    }

    return ""
  }

  private extractRelationships(content: string, filePath: string): KnowledgeGraphRelationship[] {
    const relationships: KnowledgeGraphRelationship[] = []
    const fileName = basename(filePath)

    // Pattern 1: Direct references (imports, requires)
    const importPatterns = [
      /(?:import|require)\s*[\[("']([^"')]+)[\]")']/g,
      /from\s+[\"']([^\"']+)[\"']/g,
      /import\s+.*\s+from\s+[\"']([^\"']+)[\"']/g
    ]

    importPatterns.forEach(pattern => {
      let match
      while ((match = pattern.exec(content)) !== null) {
        const moduleName = match[1]
        if (moduleName && !moduleName.startsWith(".")) {
          // External module/reference
          relationships.push({
            sourceId: fileName,
            targetId: moduleName,
            type: "references",
            confidence: 0.9,
            description: `References external module: ${moduleName}`
          })
        } else if (moduleName && moduleName.startsWith("./")) {
          // Relative file reference
          const relativePath = join(dirname(filePath), moduleName)
          relationships.push({
            sourceId: fileName,
            targetId: basename(relativePath),
            type: "references",
            confidence: 0.8,
            description: `References local file: ${moduleName}`
          })
        }
      }
    })

    // Pattern 2: Markdown links
    const linkPattern = /\[([^\]]+)\]\(([^)]+)\)/g
    let linkMatch
    while ((linkMatch = linkPattern.exec(content)) !== null) {
      const linkText = linkMatch[1]
      const linkUrl = linkMatch[2]

      // Skip external links
      if (!linkUrl.startsWith("http")) {
        relationships.push({
          sourceId: fileName,
          targetId: linkUrl,
          type: "references",
          confidence: 0.7,
          description: `Links to: ${linkText}`
        })
      }
    }

    // Pattern 3: Explicit references
    const referencePattern = /(?:see|refer to|reference|cf\.?)\s*:?\s*[\"']?([^\"'\s\n\r]+)[\"']?/gi
    let refMatch
    while ((refMatch = referencePattern.exec(content)) !== null) {
      const reference = refMatch[1]
      if (reference && reference.length > 2) {
        relationships.push({
          sourceId: fileName,
          targetId: reference,
          type: "references",
          confidence: 0.6,
          description: `References: ${reference}`
        })
      }
    }

    // Pattern 4: Technology/stack mentions (creates/uses relationships)
    const techPatterns = [
      { keyword: "uses", pattern: /uses\s+([a-zA-Z0-9\-_.]+)/gi },
      { keyword: "depends on", pattern: /depends\s+on\s+([a-zA-Z0-9\-_.]+)/gi },
      { keyword: "built with", pattern: /built\s+with\s+([a-zA-Z0-9\-_.]+)/gi },
      { keyword: "powered by", pattern: /powered\s+by\s+([a-zA-Z0-9\-_.]+)/gi }
    ]

    techPatterns.forEach(tech => {
      let match
      while ((match = tech.pattern.exec(content)) !== null) {
        const techName = match[1]
        relationships.push({
          sourceId: fileName,
          targetId: techName,
          type: tech.keyword === "uses" ? "uses" :
                  tech.keyword === "depends on" ? "depends_on" :
                  tech.keyword === "built with" ? "creates" : "uses",
          confidence: 0.7,
          description: `${tech.keyword}: ${techName}`
        })
      }
    })

    return relationships
  }

  private addFileReferences(node: KnowledgeGraphNode, relationships: KnowledgeGraphRelationship[]): void {
    // In a full implementation, this would examine file content for @see, @link, etc.
    // For now, we've already handled references in extractRelationships
  }

  private getPrimaryCategory(contentLower: string, detectedCategories: string[], frontmatter: Record<string, any>, categories: Record<string, string[]>): string {
    // Check frontmatter for explicit category hints
    if (frontmatter.category) {
      return frontmatter.category
    }

    if (frontmatter.tags && Array.isArray(frontmatter.tags)) {
      // Check if any tags match our categories
      for (const tag of frontmatter.tags) {
        const tagLower = tag.toLowerCase()
        for (const [category, keywords] of Object.entries(categories)) {
          if (keywords.some(kw => tagLower.includes(kw))) {
            return category
          }
        }
      }
    }

    // Choose category with most keyword matches
    if (detectedCategories.length > 0) {
      let bestCategory = detectedCategories[0]
      let maxMatches = 0

      for (const category of detectedCategories) {
        const keywords = categories[category] || []
        let matches = 0
        for (const keyword of keywords) {
          if (contentLower.includes(keyword.toLowerCase())) {
            matches++
          }
        }
        if (matches > maxMatches) {
          maxMatches = matches
          bestCategory = category
        }
      }

      return bestCategory
    }

    // Default fallback
    return "documentation"
  }

  private analyzeSentiment(content: string): string {
    const lower = content.toLowerCase()
    const positiveWords = ["great", "excellent", "exciting", "promising", "beautiful", "clever", "innovative", "amazing", "fantastic", "wonderful", "success", "effective", "efficient"]
    const negativeWords = ["bad", "poor", "difficult", "complex", "problematic", "issue", "error", "fail", "failure", "broken", "slow", "inefficient", "confusing"]

    const positiveCount = (lower.match(new RegExp(`\\b(${positiveWords.join("|")})\\b`, "gi")) || []).length
    const negativeCount = (lower.match(new RegExp(`\\b(${negativeWords.join("|")})\\b`, "gi")) || []).length

    if (positiveCount > negativeCount) return "positive"
    if (negativeCount > positiveCount) return "negative"
    return "neutral"
  }

  private determineTechnicalLevel(content: string): "beginner" | "intermediate" | "advanced" {
    const lower = content.toLowerCase()

    const advancedIndicators = [
      "microservice", "distributed", "concurrent", "async", "parallel", "stream", "reactive",
      "domain-driven", "event-driven", "cqrs", "event sourcing", "axon", "nestjs", "prisma", "typeorm",
      "graphql", "gql", "rpc", "grpc", "http/2", "tls", "mqtt", "kafka", "redis", "pubsub", "raft", "paxos",
      "bft", "consensus", "transformer", "attention", "bert", "gpt", "llm", "neural", "deep", "reinforcement",
      "computer vision", "object detection", "automated", "machine learning", "neural network"
    ]

    const intermediateIndicators = [
      "component", "module", "service", "layer", "interface", "protocol", "middleware",
      "authentication", "authorization", "validation", "serialization", "deserialization",
      "caching", "indexing", "querying", "aggregation", "partitioning",
      "repository", "dao", "unit testing", "integration testing", "framework", "api", "rest", "graphql"
    ]

    const beginnerIndicators = [
      "hello world", "introduction", "basics", "tutorial", "example", "starter",
      "simple", "basic", "first", "how to", "getting started", "overview"
    ]

    if (lower.match(new RegExp(`\\b(${advancedIndicators.join("|")})\\b`, "gi"))) {
      return "advanced"
    } else if (lower.match(new RegExp(`\\b(${intermediateIndicators.join("|")})\\b`, "gi"))) {
      return "intermediate"
    } else if (lower.match(new RegExp(`\\b(${beginnerIndicators.join("|")})\\b`, "gi"))) {
      return "beginner"
    }

    // Default to intermediate for anything complex but not clearly advanced
    return "intermediate"
  }

  private detectSignificance(content: string): boolean {
    // Look for markers of important content
    const significanceMarkers = [
      "architecture", "design", "structure", "implementation", "pattern", "decision",
      "strategy", "solution", "approach", "choose", "selected", "why", "because",
      "important", "critical", "essential", "vital", "must", "need", "required",
      "specification", "requirement", "constraint", "guideline", "best practice",
      "algorithm", "data structure", "complexity", "performance", "optimization",
      "security", "authentication", "authorization", "encryption", "validation"
    ]

    const lower = content.toLowerCase()
    return significanceMarkers.some(marker => lower.includes(marker))
  }

  private calculateConfidence(metadata: any, content: string): number {
    let confidence = 0.8

    // Check for internal consistency
    if (!metadata.title || metadata.title === metadata.filePath) confidence -= 0.1
    if (!metadata.description) confidence -= 0.1
    if (metadata.category === "undefined") confidence -= 0.1

    // Check for signal vs noise
    const significance = this.detectSignificance(content)
    if (!significance) confidence -= 0.1

    // Boost confidence for substantial content
    const wordCount = this.countWords(content)
    if (wordCount > 500) confidence += 0.1
    else if (wordCount > 100) confidence += 0.05

    // Boost for having frontmatter
    if (content.startsWith("---") && content.includes("\n---\n")) {
      confidence += 0.05
    }

    // Ensure confidence stays within 0-1 bounds
    return Math.max(0.1, Math.min(1, confidence))
  }

  private extractTechnologies(content: string): Technology[] {
    const techStack: Technology[] = []

    // Use string literals directly instead of object properties
    const techPatterns: Array<{ type: Technology['type']; regex: RegExp; name: string; version?: string }> = [
      { type: "language", regex: /typescript/gi, name: "TypeScript" },
      { type: "language", regex: /javascript/gi, name: "JavaScript" },
      { type: "language", regex: /python/gi, name: "Python" },
      { type: "language", regex: /go/gi, name: "Go" },
      { type: "language", regex: /rust/gi, name: "Rust" },
      { type: "language", regex: /java/gi, name: "Java" },
      { type: "language", regex: /c#/gi, name: "C#" },
      { type: "framework", regex: /next\.js/gi, name: "Next.js", version: "15" },
      { type: "framework", regex: /react/gi, name: "React", version: "18" },
      { type: "framework", regex: /vue/gi, name: "Vue", version: "3" },
      { type: "framework", regex: /angular/gi, name: "Angular", version: "16" },
      { type: "framework", regex: /express/gi, name: "Express", version: "4" },
      { type: "framework", regex: /koa/gi, name: "Koa", version: "2" },
      { type: "framework", regex: /nest/gi, name: "NestJS", version: "10" },
      { type: "framework", regex: /fastify/gi, name: "Fastify", version: "4" },
      { type: "database", regex: /postgres/gi, name: "PostgreSQL", version: "16" },
      { type: "database", regex: /mysql/gi, name: "MySQL", version: "8" },
      { type: "database", regex: /mongodb/gi, name: "MongoDB", version: "7" },
      { type: "database", regex: /sqlite/gi, name: "SQLite", version: "3" },
      { type: "service", regex: /aws/gi, name: "AWS" },
      { type: "service", regex: /azure/gi, name: "Azure" },
      { type: "service", regex: /gcp/gi, name: "Google Cloud" },
      { type: "service", regex: /vercel/gi, name: "Vercel" },
      { type: "service", regex: /netlify/gi, name: "Netlify" },
      { type: "auth", regex: /jwt/gi, name: "JSON Web Tokens" },
      { type: "auth", regex: /oauth/gi, name: "OAuth" },
      { type: "ai", regex: /ai/gi, name: "Artificial Intelligence" },
      { type: "ai", regex: /agent/gi, name: "AI Agent" },
      { type: "ai", regex: /workflow/gi, name: "Workflow" },
      { type: "ai", regex: /mcp/gi, name: "Model Context Protocol" },
      { type: "testing", regex: /jest/gi, name: "Jest" },
      { type: "testing", regex: /playwright/gi, name: "Playwright" },
    ]

    // Match patterns against content
    for (const tech of techPatterns) {
      if (tech.regex.test(content)) {
        techStack.push({
          name: tech.name,
          type: tech.type,
          version: tech.version,
          detectedFrom: tech.regex.source,
        })
      }
    }

    // Remove duplicates based on name and type
    const uniqueTech = new Map()
    for (const tech of techStack) {
      const key = `${tech.name}:${tech.type}`
      if (!uniqueTech.has(key)) {
        uniqueTech.set(key, tech)
      }
    }

    return Array.from(uniqueTech.values())
  }

  private inferIntent(frontmatter: Record<string, any>, content: string): string {
    // Check explicit intent in frontmatter
    if (frontmatter.intent) {
      return frontmatter.intent
    }

    const lowerContent = content.toLowerCase()

    // Intent patterns
    const intentPatterns: Record<string, string[]> = {
      "tutorial": ["tutorial", "walkthrough", "guide", "how to", "learn"],
      "reference": ["reference", "documentation", "api reference", "specification"],
      "proposal": ["proposal", "plan", "design", "architecture"],
      "report": ["report", "analysis", "findings", "results"],
      "specification": ["spec", "specification", "requirements", "technical"],
      "meeting notes": ["meeting", "minutes", "notes", "agenda"],
      "retrospective": ["retrospective", "review", "lessons learned"],
      "roadmap": ["roadmap", "plan", "timeline", "milestone"]
    }

    for (const [intent, keywords] of Object.entries(intentPatterns)) {
      if (keywords.some(keyword => lowerContent.includes(keyword))) {
        return intent
      }
    }

    // Check for code patterns
    if (lowerContent.includes("```") || lowerContent.includes("function ") || lowerContent.includes("class ")) {
      return "code example"
    }

    // Default
    return "documentation"
  }

  private detectArchitecturePattern(contentLower: string): string {
    const patterns: Record<string, string[]> = {
      "microservices": ["microservice", "microservices", "distributed system"],
      "monolith": ["monolith", "monolithic", "single deployment"],
      "serverless": ["serverless", "faas", "function as a service", "lambda"],
      "event-driven": ["event-driven", "event driven", "event sourcing", "cqrs"],
      "layered": ["layered", "n-tier", "3-tier", "presentation layer", "business layer", "data layer"],
      "mvc": ["mvc", "model-view-controller", "model view controller"],
      "mvvm": ["mvvm", "model-view-viewmodel"],
      "clean architecture": ["clean architecture", "hexagonal", "ports and adapters"],
      "domain-driven": ["domain-driven design", "ddd", "domain driven"],
      "plugin": ["plugin", "extension", "addon"],
      "microfrontend": ["microfrontend", "micro frontends"]
    }

    for (const [pattern, keywords] of Object.entries(patterns)) {
      if (keywords.some(keyword => contentLower.includes(keyword))) {
        return pattern
      }
    }

    return "unknown"
  }

  public async buildKnowledgeGraph(root: string): Promise<{ metadata: { nodes: KnowledgeGraphNode[] } }> {
    const files = this.findAllMarkdownFiles(root)
    const nodes: KnowledgeGraphNode[] = []

    for (const file of files) {
      const content = readFileSync(file, 'utf8')
      const frontmatter = matter(content)
      const metadata = this.extractMetadata(frontmatter.data, content, file)

      const node: KnowledgeGraphNode = {
        id: `file-${file}`,
        type: 'file',
        filePath: file,
        title: metadata.title,
        description: metadata.description,
        category: metadata.category,
        metadata: {
          ...metadata,
          wordCount: metadata.wordCount,
          lineCount: metadata.lineCount,
          sentiment: metadata.sentiment,
          technicalLevel: metadata.technicalLevel,
          technologies: metadata.technologies,
          intent: metadata.intent,
          architecturePattern: metadata.architecturePattern
        },
        confidence: this.calculateConfidence(metadata, content),
        relationships: []
      }

      nodes.push(node)
    }

    return {
      metadata: {
        nodes: nodes
      }
    }
  }
}

export const intelligenceEngine = new ProjectIntelligenceEngine()