"use client"

import Link from "next/link"
import { ArrowRight, Cpu, FileText, Layers, GitBranch, Workflow, Shield, Sparkles, Code2 } from "lucide-react"
import { SectionHeader } from "./SectionHeader"

const CAPABILITIES = [
  { icon: Cpu, label: "Blueprint generation", description: "Generate complete project architecture from a prompt" },
  { icon: FileText, label: "Documentation", description: "Auto-generate READMEs, specs, and runbooks" },
  { icon: Layers, label: "Memory creation", description: "Build persistent project memory for AI assistants" },
  { icon: GitBranch, label: "Dependency maps", description: "Visualize architecture and file relationships" },
  { icon: Workflow, label: "Workflow expansion", description: "Turn ideas into multi-step AI workflows" },
  { icon: Shield, label: "Quality scoring", description: "Score and improve generated blueprints" },
]

export function ArchitectSection() {
  return (
    <section className="py-24 relative overflow-hidden">
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background: "radial-gradient(circle at 50% 50%, rgba(202, 138, 4, 0.06), transparent 60%)",
        }}
      />

      <div className="container mx-auto px-4 relative">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <SectionHeader
                badge="Midas Architect"
                title="Generate entire projects with AI"
                description="Describe what you want to build. Architect plans the structure, writes the files, generates documentation, and creates a reusable blueprint you can share or sell."
                align="left"
              />

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
                {CAPABILITIES.map((cap, index) => {
                  const Icon = cap.icon
                  return (
                    <div
                      key={cap.label}
                      className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10 hover:border-cta/30 transition-smooth"
                      style={{ animationDelay: `${index * 0.05}s` }}
                    >
                      <div className="w-9 h-9 rounded-lg bg-cta/10 flex items-center justify-center shrink-0">
                        <Icon className="h-4 w-4 text-cta" />
                      </div>
                      <div>
                        <div className="text-sm font-semibold text-text-primary">{cap.label}</div>
                        <div className="text-xs text-text-secondary mt-0.5">{cap.description}</div>
                      </div>
                    </div>
                  )
                })}
              </div>

              <Link
                href="/architect"
                className="group inline-flex items-center gap-2 h-12 px-6 rounded-xl bg-cta text-primary-foreground font-semibold hover:bg-cta-light hover:shadow-glow transition-all duration-300"
              >
                <Sparkles className="h-4 w-4" />
                Try Midas Architect
                <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>

            {/* Visual */}
            <div className="relative">
              <div className="relative rounded-3xl border border-white/10 bg-surface/60 backdrop-blur-xl p-6 shadow-2xl">
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cta to-cta-light flex items-center justify-center">
                    <Cpu className="h-5 w-5 text-primary-foreground" />
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-text-primary">SaaS Dashboard Blueprint</div>
                    <div className="text-xs text-text-tertiary">Generated by Midas Architect</div>
                  </div>
                  <div className="ml-auto flex gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                    <div className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
                  </div>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/5 border border-white/5">
                    <Code2 className="h-4 w-4 text-blue-400" />
                    <span className="text-sm text-text-secondary">src/app/layout.tsx</span>
                    <span className="ml-auto text-xs text-emerald-400">Generated</span>
                  </div>
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/5 border border-white/5">
                    <Code2 className="h-4 w-4 text-blue-400" />
                    <span className="text-sm text-text-secondary">src/components/Dashboard.tsx</span>
                    <span className="ml-auto text-xs text-emerald-400">Generated</span>
                  </div>
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/5 border border-white/5">
                    <Layers className="h-4 w-4 text-purple-400" />
                    <span className="text-sm text-text-secondary">lib/auth/session.ts</span>
                    <span className="ml-auto text-xs text-emerald-400">Generated</span>
                  </div>
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/5 border border-white/5">
                    <FileText className="h-4 w-4 text-cta" />
                    <span className="text-sm text-text-secondary">README.md</span>
                    <span className="ml-auto text-xs text-emerald-400">Generated</span>
                  </div>
                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/5 border border-white/5">
                    <Workflow className="h-4 w-4 text-pink-400" />
                    <span className="text-sm text-text-secondary">.github/workflows/ci.yml</span>
                    <span className="ml-auto text-xs text-emerald-400">Generated</span>
                  </div>
                </div>

                <div className="mt-6 pt-6 border-t border-white/10">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-text-tertiary">Quality Score</span>
                    <span className="text-cta font-semibold">92/100</span>
                  </div>
                  <div className="mt-2 h-1.5 bg-white/10 rounded-full overflow-hidden">
                    <div className="h-full w-[92%] rounded-full bg-gradient-to-r from-cta to-cta-light" />
                  </div>
                </div>
              </div>

              {/* Decorative glow */}
              <div className="absolute -inset-4 bg-gradient-to-r from-cta/20 to-purple-500/20 rounded-[2rem] blur-3xl -z-10 opacity-40" />
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
